# Generated by Django 4.2 on 2025-04-10 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps_accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationcode',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='verificationcode',
            name='user',
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='phone_number',
            field=models.CharField(default='00000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(max_length=6),
        ),
    ]
