services:
  ecomonitor-api:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 core.wsgi
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - ecomonitor-network
    depends_on:
      - db
    volumes:
      - static_volume:/app/static
      - media_volume:/app/apps/media

  db:
    image: postgres:13
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
    networks:
      - ecomonitor-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  ecomonitor-network:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume:
