# Generated by Django 4.2 on 2025-04-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipality',
            options={'verbose_name': 'Municipality', 'verbose_name_plural': 'Municipalities'},
        ),
        migrations.AddField(
            model_name='municipality',
            name='apparent_density',
            field=models.FloatField(blank=True, help_text='Apparent specific weight or density', null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='collection_coverage_rate_total_population',
            field=models.FloatField(blank=True, help_text='Collection coverage rate relative to total population', null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='collection_coverage_rate_urban_population',
            field=models.FloatField(blank=True, help_text='Collection coverage rate relative to urban population', null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='collection_unit_cost',
            field=models.FloatField(blank=True, help_text='Unit cost of waste collection', null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='per_capita',
            field=models.FloatField(blank=True, help_text='Per capita value', null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='per_capita_recovered_mass',
            field=models.FloatField(blank=True, help_text='Recovered mass per capita', null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='per_capita_rsu_expenses_per_inhabitant',
            field=models.FloatField(blank=True, help_text='RSU expenses per inhabitant', null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='per_capita_rsu_expenses_total_population',
            field=models.FloatField(blank=True, help_text='RSU expenses per total population', null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='population',
            field=models.PositiveIntegerField(blank=True, help_text='Total population', null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='service_coverage_rate',
            field=models.FloatField(blank=True, help_text='Service coverage rate', null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='solid_waste_generation_rate',
            field=models.FloatField(blank=True, help_text='Rate of solid waste generation', null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='tons_per_collection_sector',
            field=models.FloatField(blank=True, help_text='Tons collected per collection sector', null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='tons_per_km_collected',
            field=models.FloatField(blank=True, help_text='Tons collected per kilometer', null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='total_generated_waste',
            field=models.FloatField(blank=True, help_text='Total solid waste generated (tons)', null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='total_generated_waste_tpd',
            field=models.FloatField(blank=True, help_text='Total generated waste (tons/day)', null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='waste_disposed_in_landfill_or_dump',
            field=models.FloatField(blank=True, help_text='Waste disposed in landfill or dump (tons)', null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='waste_to_gdp_per_capita_ratio',
            field=models.FloatField(blank=True, help_text='Ratio between waste and GDP per capita', null=True),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Municipality Name'),
        ),
    ]
