# Generated by Django 4.2 on 2025-04-26 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0002_alter_municipality_options_and_more'),
        ('consortia', '0001_initial'),
        ('apps_users', '0002_remove_customuser_type_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='consortium',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='consortia.consortium', verbose_name='Consórcio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manager',
            name='consortia',
            field=models.ManyToManyField(related_name='managers', to='consortia.consortium', verbose_name='Consórcios'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='municipality',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor', to='municipalities.municipality', verbose_name='Município'),
        ),
    ]
