# Generated by Django 4.2 on 2025-04-26 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_users', '0003_monitor_consortium_alter_manager_consortia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_password', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
