# Generated by Django 4.2 on 2025-05-13 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consortia', '0001_initial'),
        ('apps_users', '0004_temporarypassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='consortium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='consortia.consortium', verbose_name='Consórcio'),
        ),
    ]
