# Generated by Django 4.2 on 2025-05-16 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consortia', '0001_initial'),
        ('apps_users', '0005_alter_monitor_consortium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='consortia',
        ),
        migrations.AddField(
            model_name='manager',
            name='consortia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='consortia.consortium', verbose_name='Consórcios'),
        ),
    ]
