# Generated by Django 4.2 on 2025-04-10 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('municipalities', '0001_initial'),
        ('consortia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecyclableComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('tetrapak_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tetrapak Quantity')),
                ('aluminum_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Aluminum Quantity')),
                ('white_paper_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='White Paper Quantity')),
                ('colored_paper_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Colored Paper Quantity')),
                ('cardboard_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cardboard Quantity')),
                ('newspaper_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Newspaper Quantity')),
                ('general_plastic_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='General Plastic Quantity')),
                ('plastic_film_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Plastic Film Quantity')),
                ('pet_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='PET Quantity')),
                ('pvc_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='PVC Quantity')),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Quantity')),
                ('consortium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recyclable_compositions', to='consortia.consortium', verbose_name='Consortium')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recyclable_compositions', to='municipalities.municipality', verbose_name='Municipality')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recyclable_compositions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Recyclable Composition',
                'verbose_name_plural': 'Recyclable Compositions',
            },
        ),
    ]
