# Generated by Django 4.2 on 2025-04-11 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0002_alter_municipality_options_and_more'),
        ('consortia', '0001_initial'),
        ('apps_users', '0002_remove_customuser_type_alter_customuser_email_and_more'),
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecyclableComposition',
            new_name='RecyclableCompositionForm',
        ),
        migrations.AlterField(
            model_name='recyclablecompositionform',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recyclable_compositions', to='apps_users.monitor', verbose_name='User'),
        ),
    ]
