# Generated by Django 4.2 on 2025-04-26 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_users', '0003_monitor_consortium_alter_manager_consortia_and_more'),
        ('municipalities', '0002_alter_municipality_options_and_more'),
        ('consortia', '0001_initial'),
        ('forms', '0002_rename_recyclablecomposition_recyclablecompositionform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('zip_code', models.CharField(max_length=10)),
                ('final_destination', models.CharField(choices=[('landfill', 'Aterro'), ('dump', 'Lixão'), ('none', 'Sem destinação')], default='none', max_length=10, verbose_name='Final Destination')),
                ('selective_collection', models.BooleanField()),
                ('average_waste_per_capita', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('dry_waste_per_capita', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('organic_waste_per_capita', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('reject_waste_per_capita', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('average_payment_per_ton', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dont_know_payment', models.BooleanField(default=False)),
                ('has_recycling_program', models.BooleanField()),
                ('recycling_program_info', models.CharField(blank=True, max_length=255, null=True)),
                ('scavenger_association', models.CharField(blank=True, max_length=255, null=True)),
                ('consortium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recyclable_compositions', to='consortia.consortium', verbose_name='Consortium')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recyclable_compositions', to='municipalities.municipality', verbose_name='Municipality')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recyclable_compositions', to='apps_users.monitor', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Recyclable Composition',
                'verbose_name_plural': 'Recyclable Compositions',
            },
        ),
        migrations.DeleteModel(
            name='RecyclableCompositionForm',
        ),
    ]
