# Generated by Django 4.2 on 2025-04-27 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_form1_delete_recyclablecompositionform'),
    ]

    operations = [
        migrations.AddField(
            model_name='form1',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
