# Generated by Django 4.2 on 2025-05-06 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0002_alter_municipality_options_and_more'),
        ('apps_users', '0004_temporarypassword'),
        ('consortia', '0001_initial'),
        ('forms', '0004_form1_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecyclableWasteComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quantity_tetrapak', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_aluminum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_white_paper', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_colored_paper', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_cardboard', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_newspaper', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_general_plastic', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_film_plastic', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_pet', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_pvc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consortium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recyclable_compositions', to='consortia.consortium', verbose_name='Consortium')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recyclable_compositions', to='municipalities.municipality', verbose_name='Municipality')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recyclable_compositions', to='apps_users.monitor', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Recyclable Composition',
                'verbose_name_plural': 'Recyclable Compositions',
            },
        ),
        migrations.DeleteModel(
            name='Form1',
        ),
    ]
